version: "3.9"

services:
  main-source:
    image: alexburlacu/rtp-server:faf18x

  message-broker:
    container_name: message-broker
    depends_on:
      - main-source
    build:
      context: ./message_broker
      dockerfile: dockerfile.yml
    volumes:
      - ./message_broker/src:/broker/src
    working_dir: /broker
    tty: true
    command: rebar3 shell

  twitter-stream:
    container_name: twitter-stream
    depends_on:
      - message-broker
    build:
      context: ./twitter_stream
      dockerfile: dockerfile.yml
    volumes:
      - ./twitter_stream/src:/stream/src
    working_dir: /stream
    tty: true
    command: rebar3 shell

  client1:
    container_name: client-1
    depends_on:
      - twitter-stream
    build:
      context: ./client1
      dockerfile: dockerfile.yml
    volumes:
      - ./client1:/client1
    working_dir: /client1
    tty: true
    command: rebar3 shell
