#!/bin/bash

set -e

printf "Compiling\n\n"

erlc server_connection.erl

printf "\nRunning\n\n"

erl -s server_connection start_s -noshell -s init stop
printf "\n"

# to exit erlang after function finish:
# -s init stop 